### ISSUE TITLE
本地localhost部署支持

### ISSUE THREAD

**Issue by terwer** [lvxianchao/confluence-markdown-editor#1]
本地部署的时候，输入 http://localhost:8090 ，会校验域名不正确。

![image](https://user-images.githubusercontent.com/3259282/149443907-13f6cf4a-ecc7-4d89-b67c-30c85869f8cc.png)

建议本地部署url跳过域名校验。

**Comment by lvxianchao** [comment]
建议你使用 `127.0.0.1` 。

**Comment by terwer** [comment]
非常感谢，这种方式可以。感谢作者提供这个好用的插件。
