### ISSUE TITLE
设置了主题地址样式不生效

### ISSUE THREAD

**Issue by zhangyanni666** [lvxianchao/confluence-markdown-editor#4]

**Comment by lvxianchao** [comment]
有具体描述吗？版本号是多少？主题地址是什么？

**Comment by zhangyanni666** [comment]
> 有具体描述吗？版本号是多少？主题地址是什么？

主题地址：https://github.com/zhangyanni666/markdown-css/raw/main/intro.css
版本号：3.2.2

**Comment by lvxianchao** [comment]
如果你在插件里直接输入这个地址的话肯定是不行的，应该输入 `https://raw.githubusercontent.com/zhangyanni666/markdown-css/main/intro.css`，要小心，这个真实的文件地址域名在中国大陆是被屏蔽的，请确保你的网络可以访问得到。

**Comment by lvxianchao** [comment]
如果你发现你无法访问 `https://raw.githubusercontent.com/zhangyanni666/markdown-css/main/intro.css` 这个地址，可以尝试添加以下 host:

```shell
185.199.108.133 raw.githubusercontent.com
185.199.109.133 raw.githubusercontent.com
185.199.110.133 raw.githubusercontent.com
185.199.111.133 raw.githubusercontent.com
```
